# Generated by Django 5.2.1 on 2025-06-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_alter_incident_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='image',
        ),
        migrations.AddField(
            model_name='incident',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cloudinary Public ID'),
        ),
        migrations.AddField(
            model_name='incident',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL de la Imagen'),
        ),
    ]
